export const data = [
  {
    bodyCard: "./Pic.png",
    playerName: "RONALDO",
    playerImg: "./SUIII.png",
    country: "./Portugal.png",
    Team: "./al-nasr.png",
    pStats: 94,
    pPosition: "ST",
    pac: 90,
    sho: 93,
    pas: 82,
    dri: 90,
    def: 33,
    phy: 80,
  },
  {
    bodyCard: "./Pic.png",
    playerName: "MESSI",
    playerImg: "./Messi1.png",
    country: "./Argentina.png",
    Team: "./Barcelona.png",
    pStats: 94,
    pPosition: "ST",
    pac: 90,
    sho: 93,
    pas: 82,
    dri: 90,
    def: 33,
    phy: 80,
  },
  {
    bodyCard: "./Pic.png",
    playerName: "HALAND",
    playerImg: "./haland.png",
    country: "./Flag_of_Norway.png",
    Team: "./Borussia_Dortmund.png",
    pStats: 94,
    pPosition: "ST",
    pac: 90,
    sho: 93,
    pas: 82,
    dri: 90,
    def: 33,
    phy: 80,
  },
  // { 
  //   bodyCard: "./pic2.png",
  //   playerName: "ARBI",
  //   playerImg: "./arbii1.png",
  //   country: "./tunisia.png",
  //   Team: "./est.png",
  //   pStats: 99,
  //   pPosition: "ST",
  //   pac: 99,
  //   sho: 99,
  //   pas: 99,
  //   dri: 99,
  //   def: 99,
  //   phy: 99,
  // },
];
